### ISSUE TITLE
How to deploy the frontend and backend

### ISSUE THREAD

**Issue by alphaaman** [BobsProgrammingAcademy/freelance-developer-website#2]
I wanted to deploy the frontend on netlify but the build is not succeeding with some error. 

Here is the screenshot.
![image](https://user-images.githubusercontent.com/70965254/202858246-d0b50583-b3e1-4cd2-8aa9-4988c9574171.png)

Can you please guide me on deploying the frontend and backend?

**Comment by BobsProgrammingAcademy** [comment]
Thank you for bringing this to our attention. We've added a fix.

Now when you run the **npm run build** command, it will bundle the frontend part (the React app) into static files for production.

Here are the screenshots:

<img width="792" alt="Screenshot 2022-11-30 at 16 04 44" src="https://user-images.githubusercontent.com/97769721/204850214-c88c280d-09b5-4b29-acb9-ee91300e8b72.png">

<img width="197" alt="Screenshot 2022-11-30 at 16 05 13" src="https://user-images.githubusercontent.com/97769721/204850293-0d95b94b-767d-4a6d-8f87-7ca6a2e1789b.png">


Regarding your request - to guide you through the deployment of the frontend and backend - there are plenty of great online tutorials (including many YouTube videos) on how to deploy React frontend and Django backend to various hosting platforms. We recommend you check those.
